name: CD Fake
on:
  workflow_dispatch:
    # inputs:
    #   ambiente:
    #     type: choice
    #     options:
    #       - homologacao
    #       - producao
jobs:
  deploy-fake-homolog:
    runs-on: ubuntu-latest
    # environment: ${{ inputs.ambiente }}
    environment: homologacao
    steps:
      - name: Fake de deploy em ambiente
        run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
  teste-fake:
    runs-on: ubuntu-latest
    needs: [deploy-fake-homolog]
    environment: homologacao
    steps:
      - name: Fake de teste em ambiente
        run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"
  deploy-fake-producao:
    runs-on: ubuntu-latest
    needs: [teste-fake]
    environment: homologacao
    steps:
      - name: Fake de deploy em ambiente
        run: echo "Deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"